/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import DeviceResponse from './model/DeviceResponse';
import LocationResponse from './model/LocationResponse';
import UserRequest from './model/UserRequest';
import UserResponse from './model/UserResponse';
import DeviceControllerApi from './api/DeviceControllerApi';
import HomeControllerApi from './api/HomeControllerApi';
import UserControllerApi from './api/UserControllerApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var OpenApiDefinition = require('index'); 
* var xxxSvc = new OpenApiDefinition.XxxApi(); 
* var yyyModel = new OpenApiDefinition.Yyy(); 
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); 
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new OpenApiDefinition.XxxApi(); 
* var yyy = new OpenApiDefinition.Yyy(); 
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); 
* ...
* </pre>
* </p>
* @module index
* @version v0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The DeviceResponse model constructor.
     * @property {module:model/DeviceResponse}
     */
    DeviceResponse,

    /**
     * The LocationResponse model constructor.
     * @property {module:model/LocationResponse}
     */
    LocationResponse,

    /**
     * The UserRequest model constructor.
     * @property {module:model/UserRequest}
     */
    UserRequest,

    /**
     * The UserResponse model constructor.
     * @property {module:model/UserResponse}
     */
    UserResponse,

    /**
    * The DeviceControllerApi service constructor.
    * @property {module:api/DeviceControllerApi}
    */
    DeviceControllerApi,

    /**
    * The HomeControllerApi service constructor.
    * @property {module:api/HomeControllerApi}
    */
    HomeControllerApi,

    /**
    * The UserControllerApi service constructor.
    * @property {module:api/UserControllerApi}
    */
    UserControllerApi
};
