/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/PBR5bGamwFR
 */
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function profile() {
  return (
    <Card className="mx-auto max-w-md space-y-6 p-6">
      <CardHeader>
        <h1 className="text-3xl font-bold">Food Information Registration</h1>
        <p className="text-gray-500 dark:text-gray-400">Enter your information and food preferences</p>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="name">Name</Label>
              <Input id="name" placeholder="John Doe" required />
            </div>
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input id="email" placeholder="johndoe@example.com" required type="email" />
            </div>
          </div>
          <div className="space-y-2">
            <Label htmlFor="password">Password</Label>
            <Input id="password" required type="password" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="food-preferences">Food Preferences</Label>
            <Input id="food-preferences" placeholder="Vegetarian, Gluten-free, etc." />
          </div>
          <div className="space-y-2">
            <Label htmlFor="dietary-restrictions">Dietary Restrictions</Label>
            <Input id="dietary-restrictions" placeholder="Lactose Intolerant, Nut Allergy, etc." />
          </div>
          <Button className="w-full" type="submit">
            Register
          </Button>
        </div>
      </CardContent>
    </Card>
  )
}
